class ModelsVO:

    LINEAR_RGRESSION: str = "linear_regression"
    DECISON_TREE_REGRESSION: str = "decision_tree_regression"
    SVR: str = "svr"
    RANDOM_FOREST_REGRESSION: str = "random_forest_regression"
    GRADIEN_BOOSTING_REGRESSION:str = "gradien_boosting_regresion"
    RIDGE:str = "ridge"
    LASSO:str = "lasso"
    ELASTIC_NET:str = "elastic_net"
    SGD_REGRESSION:str = "sgd_regression"
    K_NEIGHBORS_REGRESSION:str = "k_neighbors_regression"
    EXTRACT_TREES_REGRESSOR:str = "extract_trees_regressor"
    KERNEL_RIDGE:str = "kernel_ridge"
    MLP_REGRESSOR:str = "mlp_regressor"
    ADA_BOOST_REGRESSOR:str = "ada_boost_regressor"
    BIGGINING_REGRESSOR:str = "biggining_regressor"
    GAUSSIAN_PROCESS_REGRESSOR:str = "gaussian_process_regressor"
    RANSAC_REGRESSOR:str = "rnsac_regressor"
    COSTUM_LSTM_MODEL:str = "costum_lstm_model"